name: PyPI publish

on:
    release:
        types: [published]

jobs:
    build-n-publish:
        name: Build python package
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup
              run: pip3 install setuptools wheel twine

            - name: Build
              env:
                  PYPI_VERSION: ${{ github.ref }}
              run: python3 setup.py bdist_wheel sdist

            - name: Upload
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
              run: twine upload dist/*

            - name: Clean up
              run: rm -rf dist build module.egg-info
